export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const REQUEST_SURVEY_LIST = 'REQUEST_SURVEY_LIST'
export const RECEVIE_SURVEY_LIST = 'RECEVIE_SURVEY_LIST'

export const REQUEST_TABLE_LIST = 'REQUEST_TABLE_LIST'
export const RECEVIE_TABLE_LIST = 'RECEVIE_TABLE_LIST'
